//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowServerProcessHistory
    {
        public System.Guid Id { get; set; }
        public System.Guid ProcessId { get; set; }
        public string IdentityId { get; set; }
        public string AllowedToEmployeeNames { get; set; }
        public Nullable<System.DateTime> TransitionTime { get; set; }
        public long Order { get; set; }
        public string InitialState { get; set; }
        public string DestinationState { get; set; }
        public string Command { get; set; }
    
        public virtual WorkflowServerProcessHistory WorkflowServerProcessHistory1 { get; set; }
        public virtual WorkflowServerProcessHistory WorkflowServerProcessHistory2 { get; set; }
    }
}
