//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowScheme
    {
        public string Code { get; set; }
        public string Scheme { get; set; }
        public bool CanBeInlined { get; set; }
        public string InlinedSchemes { get; set; }
        public bool DeleteFinalized { get; set; }
        public bool DontFillIndox { get; set; }
        public bool DontPreExecute { get; set; }
    }
}
