//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowServerStat
    {
        public System.Guid Id { get; set; }
        public string Type { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public int Duration { get; set; }
        public bool IsSuccess { get; set; }
        public Nullable<System.Guid> ProcessId { get; set; }
    }
}
