/**
 * Workflow Server API
 * Describes the basic methods for managing WorkflowEngine processes
 *
 * OpenAPI spec version: 2.3.0
 * Contact: sales@optimajet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface OperationResult { 
    /**
     * Indicates whether the operation was successful or not
     */
    success: boolean;
    /**
     * The short description of the error
     */
    error?: string;
    /**
     * The details of the error
     */
    message?: string;
}

export interface ProcessParameters { 
}